app_logout:
    path: /logout
    methods: GET
login:
    path:       /login
    controller: App\Controller\LoginController::showForm

protected_route:
    path: /protected
    controller: App\Controller\ProtectedPartController::protectedZone
